version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:alpine-3.9-ocaml-4.07
    working_directory: ~/repo
    steps:
      - run:
          name: Install System Dependencies
          command: sudo apk add --no-cache m4
      - checkout
      - run:
          name: Install
          command: eval `opam config env` && opam pin add -y orandom .
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: ocaml/opam2:alpine-3.9-ocaml-4.07
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Unit testing
          command: eval `opam config env` && dune runtest test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
